src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if the category is visible/usable.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Language__c.object
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TextBlock__c.object
<CustomObject>
    <fields>
        <fullName>AvailableForProfiles__c</fullName>
        <label>Available for profiles</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuickCode__c</fullName>
        <label>Quick Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceCountry__c</fullName>
        <globalPicklist>ServiceCountry</globalPicklist>
        <label>Service Country</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TextBlockName__c</fullName>
        <label>Text Block Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextContent__c</fullName>
        <label>Text Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text Block</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sample Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Text Block</label>
    <nameField>
        <displayFormat>TB-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TextBlockItem__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Text Block Category Assignments</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TextBlockName__c</fullName>
        <label>Text Block Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextBlock__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Text Block</label>
        <referenceTo>TextBlock__c</referenceTo>
        <relationshipLabel>Text Block Items</relationshipLabel>
        <relationshipName>Text_Block_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Text Block Item</label>
    <nameField>
        <displayFormat>TBI-{000000000}</displayFormat>
        <label>Text Block Item</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TextBlocksService.cls
/**
*   @description Wrapper class over 'TextBlock__c' and 'TextBlockItem__c' sobjects for related and potentially reusable logic.

*/
public with sharing class TextBlocksService 
{
    public static Set<String> getTextBlockItemBaseFieldsApis()
    {
        return new Set<String>{
            'TextBlock__r.TextBlockName__c', 'TextBlock__r.TextContent__c', 'TextBlock__c, Category__r.Name',
            'Category__c', 'TextBlock__r.ServiceCountry__c', 'TextBlock__r.Type__c', 'TextBlock__r.QuickCode__c',
            'TextBlock__r.AvailableForProfiles__c'
        };
    }

    /**
    *    @description Returns 'TextBlockItem__c' records by category, country code and language criteria.
    */
    public static List<TextBlockItem__c> getActiveCategoryAndCountryCodeRelatedTextBlockItemsByLng(Set<String> fields, String serviceCountryCode, Id lngId, Boolean includeWithoutLng)
    {
        Set<String> targetFields = getTextBlockItemBaseFieldsApis();
        targetFields.addAll(fields);
        targetFields.add('Id');

        String query = 'SELECT ';
        query += String.join(new List<String>(targetFields), ',');
        query += ' FROM TextBlockItem__c';
        query += ' WHERE Category__r.IsActive__c = true';
        if (String.isNotBlank(lngId))
        {
            query += ' AND ';
            if (includeWithoutLng != null && includeWithoutLng)
            {
                query += '(TextBlock__r.Language__c = NULL OR ';
            }
            query += 'TextBlock__r.Language__c =: lngId';
            query += includeWithoutLng != null && includeWithoutLng ? ')' : '';
        }
        query += ' LIMIT ' + (Limits.getLimitQueryRows() - Limits.getQueryRows());

        System.debug('++++++:query '+query);
        return (List<TextBlockItem__c>)Database.query(query);
    }
}