src/objects/MessageInApproval__c.object
<CustomObject>
    <fields>
        <fullName>Bcc__c</fullName>
        <label>Bcc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cc__c</fullName>
        <label>Cc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextContent__c</fullName>
        <label>Text Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Message in Approval</label>
    <nameField>
        <label>Message in Approval Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MessageInApprovalAfterHandler.cls
/*
*   @description MessageInApprovalAfterHandler
*
*   @author mto
*   @copyright PARX
*/
public with sharing class MessageInApprovalAfterHandler implements TriggerTemplateV2.AfterTriggerHandler {
    
    public void onAfterInsert (List<sObject> newList, Map<Id, sObject> newMap)
    {
        TriggerTemplateV2.setupUnitTest();
        for(sObject obj : newList)
        {
            MessageInApproval__c mia = (MessageInApproval__c) obj;
            setWaitingForApproval(mia);
        }

    }
    
    public void onAfterUpdate (List<sObject> newList, Map<Id, sObject> newMap, List<sObject> oldList, Map<Id, sObject> oldMap)
    {
        TriggerTemplateV2.setupUnitTest();
        for(sObject obj : newList)
        {
            MessageInApproval__c mia = (MessageInApproval__c) obj;
            setWaitingForApproval(mia);
        }
    }

    /**
    *    @description DE32. Moved soql from for loop.
    */

    
    public void onAfterDelete (List<sObject> oldList, Map<Id, sObject> oldMap)
    {

    }

    public void onAfterUndelete (List<sObject> newList, Map<Id, sObject> newMap)
    {

    }

    @TestVisible
    private static void setWaitingForApproval(MessageInApproval__c mia)
    {
        if(mia.Status__c == 'Approved')
        {
            Message message = sendEmail(mia);

            if(message.errorMessage != null)
            {
                mia.addError(message.errorMessage);
                return;
            }
        }
    }

    private static Message sendEmail(MessageInApproval__c messageInApproval)
    {
        String fromAddressId = '';
        if(String.isNotEmpty(messageInApproval.From__c))
        {
            OrgWideEmailAddress[] fromAddresses = [select Id, Address from OrgWideEmailAddress where Address = :messageInApproval.From__c];
            if(fromAddresses != null && fromAddresses.size() == 1)
            {
                fromAddressId = fromAddresses[0].Id;
            }
        }

        List<AttachmentItem> attachments = AttachmentsService.wrapAttachmentsForSelectionOnUI(AttachmentsService.getRecordRelatedAttachments(messageInApproval.Id, true));

        ComunicationService communicationService = new ComunicationService();

        return communicationService.sendEmail(
                messageInApproval.To__c,
                messageInApproval.Cc__c,
                messageInApproval.Bcc__c,
                messageInApproval.Subject__c,
                messageInApproval.TextContent__c,
                attachments
        );
    }

}