src/objects/Movie__c.object
<CustomObject>
    <fields>
        <fullName>Director__c</fullName>
        <label>Director</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShowTime__c</fullName>
        <label>ShowTime</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToStar__c</fullName>
        <label>ToStar</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MovieController.cls
public class MovieController {
    
    @AuraEnabled
    public static List<Movie__c> GetAll(){
        List<Movie__c> movieList = new List<Movie__c>();
        movieList = [SELECT ShowTime__c, ToStar__c, Theme__c, Director__c, Name 
                    FROM Movie__c LIMIT 100];
        
        return movieList;
    }
    
    @AuraEnabled
    public static Movie__c saveMovie(Movie__c movie){
        upsert movie;
        return movie;
    }

}